include:
  - Driving.Frontend/compose.yaml

services:
  drivingservice:
    image: drivingservice
    build:
      context: .
      dockerfile: Driving.Service/Dockerfile
      args:
        - configuration=Debug
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword;
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - logs:/app/logs
  
  drivingapi:
    image: drivingapi
    build:
      context: .
      dockerfile: Driving.Api/Dockerfile
      args:
        - configuration=Debug
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword;
    ports:
      - "8080:8080"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - logs:/app/logs

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d mydatabase -U myuser" ]
      interval: 5s
      timeout: 5s
      retries: 8

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak:/opt/keycloak/data
    ports:
      - 18080:8080

volumes:
  postgres_data:
  logs:
  keaycloak:
