/* tslint:disable */
/* eslint-disable */
/**
 * Driving.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTagCommand
 */
export interface CreateTagCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateTagCommand
     */
    name?: string;
}

/**
 * Check if a given object implements the CreateTagCommand interface.
 */
export function instanceOfCreateTagCommand(value: object): boolean {
    return true;
}

export function CreateTagCommandFromJSON(json: any): CreateTagCommand {
    return CreateTagCommandFromJSONTyped(json, false);
}

export function CreateTagCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTagCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CreateTagCommandToJSON(value?: CreateTagCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

