/* tslint:disable */
/* eslint-disable */
/**
 * Driving.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProjectSource = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type ProjectSource = typeof ProjectSource[keyof typeof ProjectSource];


export function instanceOfProjectSource(value: any): boolean {
    return Object.values(ProjectSource).includes(value);
}

export function ProjectSourceFromJSON(json: any): ProjectSource {
    return ProjectSourceFromJSONTyped(json, false);
}

export function ProjectSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSource {
    return json as ProjectSource;
}

export function ProjectSourceToJSON(value?: ProjectSource | null): any {
    return value as any;
}

