/* tslint:disable */
/* eslint-disable */
/**
 * Driving.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTagCommand,
  ProblemDetails,
  Tag,
} from '../models/index';
import {
    CreateTagCommandFromJSON,
    CreateTagCommandToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    TagFromJSON,
    TagToJSON,
} from '../models/index';

export interface IdDeleteRequest {
    id: number;
}

export interface TagCreatePostRequest {
    createTagCommand?: CreateTagCommand;
}

/**
 * 
 */
export class TagApi extends runtime.BaseAPI {

    /**
     */
    async idDeleteRaw(requestParameters: IdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Tag>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling idDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TagFromJSON));
    }

    /**
     */
    async idDelete(requestParameters: IdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Tag>> {
        const response = await this.idDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async tagAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Tag>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tag/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TagFromJSON));
    }

    /**
     */
    async tagAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Tag>> {
        const response = await this.tagAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async tagCreatePostRaw(requestParameters: TagCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/tag/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTagCommandToJSON(requestParameters['createTagCommand']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async tagCreatePost(requestParameters: TagCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.tagCreatePostRaw(requestParameters, initOverrides);
    }

}
